import h5py
import argparse
import numpy as np
from netCDF4 import Dataset
import sys

def get_cris_chan_from_iasi(cris_chan, iasi_chan, output_file = None, iasi_sps_chan=None):
    
    CHAN_THRESHOLD = 0.2
    
    out_chan = []
    for ichan in iasi_chan:
        dif = np.abs( cris_chan - ichan  )
        min_dif = dif.min()
        if min_dif < CHAN_THRESHOLD:
            out_chan.append(np.argmin(dif))
    out_chan = np.unique(out_chan)
    
    
    if output_file != None:
        with open(output_file, "w") as ofile:
            try:
                np.savetxt(ofile, out_chan, fmt = "%d")
                print("Saved chan list in {}".format(output_file))
            except:
                print("Error!")
                
        
        return
    else:
        return out_chan if iasi_sps is None else out_chan, out_sps_chan



def array_twist(vect):
    """
    Given an array of data generated by the CrIS interferometer with the
    following shape: (nscan, 30, 9, ...), return an array with the shape
    (3 * nscan, 90, ...) having reshaped the array such that the data collected
    by sensors on the same scan line (for example 1, 2 and 3 or 7,8, and 9)
    is contiguous.

    :ivar vect: A nD numpy array with n > 2

    :return output: A nD numpy array where the dimension regarding the sensor
                    number of vect has been splitted among the other two
    """

    assert len(vect.shape) >= 3, 'The input array must be at least a 3D '\
                                 'array. The current shape is '\
                                 '{}'.format(vect.shape)
    nscan, scan_line, n_sensors = vect.shape[:3]
    assert scan_line == 30, 'The second dimension of the input array must be '\
                            '30. Currently is {}'.format(scan_line)
    assert n_sensors == 9, 'The last dimension of the input array must be '\
                           '9. Currently is {}'.format(n_sensors)

    output = np.empty_like(vect).reshape(nscan*3, 90, *vect.shape[3:])

    for current_scan in range(nscan):
        for line in range(0, 3):
            new_scan = current_scan*3 + line
            for i in range(3):
                output[new_scan, i::3] = vect[current_scan, :, 3*line + i]

    return output





parser = argparse.ArgumentParser()
parser.add_argument('-i', '--input', required=True,
                    help="CrIS input file")
parser.add_argument('-c', '--chan_file', required=True,
                    help="CrIS channel list")
parser.add_argument('-o', '--outfile', required=True,
                    help="ObsErr Output File")
parser.add_argument('-tr', '--out_trfile', required=False,
                    default = None,
                    help="TR ObsErr Output File")
parser.add_argument('-trc', '--tr_chan_file', required=False,
                    default = None,
                    help="TR Channel List")


argv = parser.parse_args()
sel_channel = np.loadtxt(argv.chan_file,dtype=int)

print("Computing Observation Error...")
with h5py.File(argv.input, 'r') as scris_file:
    try:
        geo_all = scris_file['All_Data/CrIS-SDR_All']
    except:
        geo_all = scris_file['All_Data/CrIS-FS-SDR_All']

    err_lw = np.array(geo_all["ES_NEdNLW"][:])
    err_lw = array_twist(err_lw)
    err_lw = err_lw.reshape((err_lw.shape[0]*err_lw.shape[1],err_lw.shape[2]),).mean(axis=0)

    err_mw = np.array(geo_all["ES_NEdNMW"][:])
    err_mw = array_twist(err_mw)
    err_mw = err_mw.reshape((err_mw.shape[0]*err_mw.shape[1],err_mw.shape[2]),).mean(axis=0)

    err_sw = np.array(geo_all["ES_NEdNSW"][:])
    err_sw = array_twist(err_sw)
    err_sw = err_sw.reshape((err_sw.shape[0]*err_sw.shape[1],err_sw.shape[2]),).mean(axis=0)

full_err = np.concatenate((err_lw, err_mw,err_sw))
obserr = np.diag( full_err[sel_channel] )
    
# Write outnetcdf

nc_fid = Dataset(argv.outfile, 'w', format='NETCDF4')
nc_fid.description = "CrIS Observation Error Covariance "
selchannels = nc_fid.createDimension('selchannels',len(sel_channel))

out_obs_err        = nc_fid.createVariable('obs_err','f4',('selchannels','selchannels'))
inv_obs_err    = nc_fid.createVariable('inv_obs_err','f4',('selchannels','selchannels'))
obs_err_U      = nc_fid.createVariable('obs_err_U','f4',('selchannels','selchannels'))
obs_err_D      = nc_fid.createVariable('obs_err_D','f4',('selchannels'))
#out_oe_sub_indices = w_nc_fid.createVariable('oe_sub_indices','f4',('selchannels'))

out_obs_err[:,:] = obserr
inv_obs_err[:,:] = np.linalg.inv(obserr)

#Get Observation Error SVD
sub_obs_err_U, sub_obs_err_D, sub_obs_err_V = np.linalg.svd(obserr, full_matrices=True)

obs_err_U[:,:]    = sub_obs_err_U
obs_err_D[:]      = sub_obs_err_D

nc_fid.close()
print("NETCDF File saved in {}".format(argv.outfile))
#ut_oe_sub_indices[:] = sel_channel

if argv.out_trfile != None:
    print("Preparing TR Observation Error...")
    
    if argv.tr_chan_file is None:
        sys.exit("I need a TR channel list file!")
    tr_selchannels = np.loadtxt(argv.tr_chan_file,dtype=int)   
    tr_obserr = obserr[tr_selchannels][tr_selchannels]
    
    nc_fid = Dataset(argv.out_trfile, 'w', format='NETCDF4')
    nc_fid.description = "CrIS TR Observation Error Covariance "
    selchannels = nc_fid.createDimension('selchannels',len(tr_selchannels))
    nc_fid.description = "The TR subselection of the Inversion Observation Error Covariance"
    
    out_obs_err        = nc_fid.createVariable('obs_err','f4',('selchannels','selchannels'))
    inv_obs_err    = nc_fid.createVariable('inv_obs_err','f4',('selchannels','selchannels'))
    obs_err_U      = nc_fid.createVariable('obs_err_U','f4',('selchannels','selchannels'))
    obs_err_D      = nc_fid.createVariable('obs_err_D','f4',('selchannels'))
    oe_sub_indices = nc_fid.createVariable('oe_sub_indices','f4',('selchannels'))
    
    out_obs_err[:,:] = tr_obserr
    inv_obs_err[:,:] = np.linalg.inv(tr_obserr)
    
    #Get Observation Error SVD
    sub_obs_err_U, sub_obs_err_D, sub_obs_err_V = np.linalg.svd(tr_obserr, full_matrices=True)
    
    obs_err_U[:,:]    = sub_obs_err_U
    obs_err_D[:]      = sub_obs_err_D
    oe_sub_indices[:] = tr_selchannels

    nc_fid.close()
    print("NETCDF File saved in {}".format(argv.out_trfile))
    
    

    

    






    