# This file is part of Cris2observations.
#
# Cris2observations is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Cris2observations is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Cris2observation. If not, see <http://www.gnu.org/licenses/>.

"""
array_reshapers module contains all the functions that are related to change
the shape of the vectors taking into account the particulary of the CrIS data
(for example, the presence of 9 sensor on the interferometer)
"""

import logging
import numpy as np

__author__ = 'Stefano Piani <stefano.piani@exact-lab.it>'
__copyright__ = "Copyright 2016, eXact-lab and Paolo Antonelli"
__credits__ = ["Stefano Piani", "Paolo Antonelli"]
__license__ = "GPL"
__maintainer__ = "Stefano Piani"
__email__ = "stefano.piani@exact-lab.it"

LOGGER = logging.getLogger(__name__)

def array_twist(vect):
    """
    Given an array of data generated by the CrIS interferometer with the
    following shape: (nscan, 30, 9, ...), return an array with the shape
    (3 * nscan, 90, ...) having reshaped the array such that the data collected
    by sensors on the same scan line (for example 1, 2 and 3 or 7,8, and 9)
    is contiguous.

    :ivar vect: A nD numpy array with n > 2

    :return output: A nD numpy array where the dimension regarding the sensor
                    number of vect has been splitted among the other two
    """

    assert len(vect.shape) >= 3, 'The input array must be at least a 3D '\
                                 'array. The current shape is '\
                                 '{}'.format(vect.shape)
    nscan, scan_line, n_sensors = vect.shape[:3]
    assert scan_line == 30, 'The second dimension of the input array must be '\
                            '30. Currently is {}'.format(scan_line)
    assert n_sensors == 9, 'The last dimension of the input array must be '\
                           '9. Currently is {}'.format(n_sensors)

    output = np.empty_like(vect).reshape(nscan*3, 90, *vect.shape[3:])

    for current_scan in range(nscan):
        for line in range(0, 3):
            new_scan = current_scan*3 + line
            for i in range(3):
                output[new_scan, i::3] = vect[current_scan, :, 3*line + i]

    return output


def array_spread(vect):
    """
    This function take care of extend the quantities that are measured
    just one time for all the sensors to an array that associates the
    same quantity to each FOV.
    Therefore, given an array of data with the following shape (nscan, 30,...),
    it returns an array with the shape (3 * nscan, 90, ...) where the value of
    each entry of the input array is replicated 9 times (3 times in the
    first dimension and 3 times in the second).

    :ivar vect: A nD numpy array with n > 1

    :return output: A nD numpy array where the values have been spreaded
    """

    assert len(vect.shape) >= 2, 'The input array must be at least a 2D '\
                                 'array. The current shape is '\
                                 '{}'.format(vect.shape)
    n_sensors_per_dim = 3

    vect = np.repeat(vect, n_sensors_per_dim, 0)
    vect = np.repeat(vect, n_sensors_per_dim, 1)

    return vect

def array_1d(vect):
    if len(vect.shape) != 3:
        return  vect.reshape(vect.size)
    else:
        return  vect.reshape((vect.shape[0]*vect.shape[1],3))
    

def transform_index(index,shape):
    if type(index) in (int, np.int32, np.int64):
        return ( index//shape[1] , (index) % shape[1] )
    else:
        return shape[1]*index[0] + index[1]