# This file is part of Wrf2firstguess.
#
# Wrf2firstguess is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Wrf2firstguess is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Wrf2firstguess. If not, see <http://www.gnu.org/licenses/>.

"""
split_by_time is the module that contains all the classes and functions that
wrf2firstguess uses to handle the problems related to associate the right time
step of the WRF model to each observation generated by the instrument
"""

import numpy as np

__author__ = 'Stefano Piani <stefano.piani@exact-lab.it>'
__copyright__ = "Copyright 2016, eXact-lab and Paolo Antonelli"
__credits__ = ["Stefano Piani", "Paolo Antonelli"]
__license__ = "GPL"
__maintainer__ = "Stefano Piani"
__email__ = "stefano.piani@exact-lab.it"

def split_by_time(values, collectors):
    """
    Given an array of different times, split it in small subarrays in such
    a way that all the values of a particular subarray have the closest
    collector point in common

    Args:
        - *values*: A not-empty 1D array of datetimes64 objects
        - *collectors*: A not-empty 1D array of datetimes64 objects

    Return:

          A list of tuples: the first element of the tuple is the index of
          a collector element, the second is the first element of the value
          array which has as closest collector the first element of the tuple,
          the third one is the last element of the value array with the same
          property
    """

    assert len(values) > 0, "No values were provided"
    assert len(collectors) > 0, "No collectors were provided"

    output = []
    # Initialize the values for the loop
    current_collector_index = np.argmin(np.abs(collectors - values[0]))
    start = 0
    # i is the index of the position that a particular value has in the
    # values array. To be coherent with the next enumerate statement,
    # we put a -1 for the first element of the array
    i = -1

    for i, val in enumerate(values[1:]):
        nearest_collector = np.argmin(np.abs(collectors - val))
        if nearest_collector != current_collector_index:
            # i+1 because enumerate starts from 1
            output.append((current_collector_index, start, i+1))
            start = i + 1
            current_collector_index = nearest_collector
    output.append((current_collector_index, start, i+2))

    return output
